version: '3.3'

services:

  caddy:
    image: caddy
    container_name: sheepit_caddy
    restart: unless-stopped
    ports:
      - ${IP}:80:80
      - ${IP}:443:443
      - ${IP}:443:443/udp
    environment:
      - IP: ${IP}
      - EMAIL: ${EMAIL}
    volumes:
      - type: bind
        source: ./Caddyfile
        target: /etc/caddy/Caddyfile
      - ./mounts/caddy-config:/config
      - /etc/localtime:/etc/localtime:ro

  binary:
    build: ./sheepit-binary-docker
    container_name: sheepit_binary
    restart: unless-stopped
    volumes:
      - ./mounts/binary:/data

  scene:
    image: sheepitrenderfarm/project-mirror
    container_name: sheepit_project
    restart: always
    volumes:
      - ./mounts/projects:/tmp/projects
      - ./mounts/project-logs:/tmp/logs
      - type: bind
        source: ./scene.conf.php
        target: /etc/sheepit-mirror/etc/config.local.inc.php
      - type: bind
        source: ./speedtest.zip
        target: /var/www/html/speedtest.zip
