version: '3.3'

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - VALIDATION=http
      - STAGING
      - URL
      - EMAIL
      - TZ
    volumes:
      - ./mounts/swag:/config
      - type: bind
        source: ./swag.conf
        target: /config/nginx/site-confs/default
    ports:
      - ${IP}:443:443
      - ${IP}:80:80
    restart: unless-stopped
    
  binary:
    build: ./sheepit-binary-docker
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./mounts/binary:/data

  scene:
    image: sheepitrenderfarm/project-mirror
    restart: always
    ports:
      - 80
    volumes:
      - ./mounts/projects:/tmp/projects
      - ./mounts/project-logs:/tmp/logs
      - type: bind
        source: ./scene.conf.php
        target: /etc/sheepit-mirror/etc/config.local.inc.php
      - type: bind
        source: ./speedtest.zip
        target: /var/www/html/speedtest.zip

